version: '2'
services:
  php:
    build: ./docker/php/
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./app:/var/www/app:cached
      - /app-vendor
    working_dir: /var/www/app
#    user: ${UID}:${GID}
#    command: bash -c 'composer install'
    restart: always

  webserver:
    image: nginx:1.11
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8000:80
    restart: always

  my_mysql:
    image: greenera/mysql_5:latest
    restart: always
    command: --max_allowed_packet=500M #todo перевірити чи так працює, чи потібно ставити байти
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    depends_on:
      - my_mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: my_mysql
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}